version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: memorise-db
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:3306"
    volumes:
          - db_data:/var/lib/mysql
          - ./memorise_gc_db.sql:/docker-entrypoint-initdb.d/memorise_gc_db.sql

volumes:
  db_data:  