name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Google Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Build and Push Docker Image
      run: |-
        gcloud builds submit \
          --tag "gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-service:$GITHUB_SHA"

    - name: Deploy to Cloud Run
      run: |-
        gcloud run deploy api-service \
          --image "gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-service:$GITHUB_SHA" \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --add-cloudsql-instances ${{ secrets.INSTANCE_CONNECTION_NAME }} \
          --set-env-vars "DB_USER=${{ secrets.DB_USER}},DB_PASSWORD=${{ secrets.DB_PASSWORD}},DB_NAME=${{ secrets.DB_NAME}},INSTANCE_CONNECTION_NAME=${{ secrets.INSTANCE_CONNECTION_NAME}}"
