name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-west4
  GAR_LOCATION: europe-west4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/memorise-repo/
jobs:
  build-and-push:
    name: Build && Push && Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Docker image tag
        id: set_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          project_id: ${{ secrets.GCP_PROJECT_ID }}
     
      - name: Configure Docker
        uses: docker/login-action@v2
        with:
          registry: europe-west4-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build Docker image
        run: |
          docker build -t europe-west4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/memorise-repo:${{ github.sha }} -f Dockerfile .
      
      - name: Push Docker image to Artifact Registry
        run: |
          docker push europe-west4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/memorise-repo:${{ github.sha }}
      
      
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: memorise-repo-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/memorise-repo:${{ github.sha }} --platform managed --allow-unauthenticated
