name: CI/CD Backend Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Build Application
        run: npm run build
      - name: Run Tests
        run: npm test
      - name: Build Docker Image
        run: docker build -t my-node-app .
      - name: Push Docker Image to Registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: my-node-app:latest
          
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to GCP
        uses: google-github-actions/deploy-to-cloud-run@v1
        with:
          # Configure GCP credentials and Cloud Run service name
          # Refer to the action's documentation for detailed configuration
          service_name: my-node-app
          image: gcr.io/my-project/my-node-app:latest
