name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: memoriseapi
  REGION: europe-west4
  FB_SERVICEACCOUNT_SECRET_NAME: ${{ secrets.FB_SERVICEACCOUNT_SECRET_NAME }}
  FB_BUCKET: ${{ secrets.FB_BUCKET }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npx eslint .

  deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }} # Use credentials_json

      - name: Set Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --set-env-vars NODE_ENV=production,GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},FB_SERVICEACCOUNT_SECRET_NAME=${{ secrets.FB_SERVICEACCOUNT_SECRET_NAME }},FB_BUCKET=${{ secrets.FB_BUCKET }}
