name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-west4
  SERVICE: memoriseapi
  GAR_LOCATION: europe-west4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/memorise-repo
jobs:
  build-and-push:
    name: Build && Push && Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Docker image tag
        id: set_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Login to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          token_format: access_token
     
      - name: Configure Docker
        uses: docker/login-action@v2
        with:
          registry: europe-west4-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.GAR_LOCATION }}/memorise-repo:${{ github.sha }} -f Dockerfile .
      
      - name: Push Docker image to Artifact Registry
        run: |
          docker push ${{ env.GAR_LOCATION }}/memorise-repo:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: europe-west4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/memorise-repo/memorise-repo:${{ github.sha }}
          flags: '--platform managed --allow-unauthenticated'
          env_vars: |-
            GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
            FB_SERVICEACCOUNT_SECRET_NAME=${{ secrets.FB_SERVICEACCOUNT_SECRET_NAME }}
            FB_BUCKET=${{ secrets.FB_BUCKET }}
            INSTANCE_CONNECTION_NAME=${{ secrets.INSTANCE_CONNECTION_NAME }}
            INSTANCE_UNIX_SOCKET=/cloudsql/${{ secrets.INSTANCE_CONNECTION_NAME }}
            NODE_ENV=production
            DB_HOST=35.205.25.203
            DB_PORT=3306
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_DATABASE=${{ secrets.DB_NAME }}